

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class AppBarButton;
                ref class TextBlock;
                ref class ComboBox;
                ref class CheckBox;
                ref class TimePicker;
                ref class DatePicker;
                ref class TextBox;
                ref class Button;
            }
        }
    }
}

namespace App1
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ EditEvents;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ SyncPage;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ categoryLabel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ airportLabel;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ categoryBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ airportBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ importantLabel;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ reportBox;
        private: ::Windows::UI::Xaml::Controls::TimePicker^ timeBox;
        private: ::Windows::UI::Xaml::Controls::DatePicker^ dateBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ timeLabel;
        private: ::Windows::UI::Xaml::Controls::TextBox^ descriptionBox;
        private: ::Windows::UI::Xaml::Controls::Button^ submitButton;
    };
}

